# ----------------------------------------
# Kokoro tts voices Configuration
# ----------------------------------------
#
#┌─────────────┬────────────┬──────────┬──────────┬────────┬───────────────┬──────────────┐
#│ (index)     │ name       │ language │ gender   │ traits │ targetQuality │ overallGrade │
#├─────────────┼────────────┼──────────┼──────────┼────────┼───────────────┼──────────────┤
#│ af_heart    │ 'Heart'    │ 'en-us'  │ 'Female' │ '❤️'   │ 'A'           │ 'A'          │
#│ af_alloy    │ 'Alloy'    │ 'en-us'  │ 'Female' │        │ 'B'           │ 'C'          │
#│ af_aoede    │ 'Aoede'    │ 'en-us'  │ 'Female' │        │ 'B'           │ 'C+'         │
#│ af_bella    │ 'Bella'    │ 'en-us'  │ 'Female' │ '🔥'   │ 'A'           │ 'A-'         │
#│ af_jessica  │ 'Jessica'  │ 'en-us'  │ 'Female' │        │ 'C'           │ 'D'          │
#│ af_kore     │ 'Kore'     │ 'en-us'  │ 'Female' │        │ 'B'           │ 'C+'         │
#│ af_nicole   │ 'Nicole'   │ 'en-us'  │ 'Female' │ '🎧'   │ 'B'           │ 'B-'         │
#│ af_nova     │ 'Nova'     │ 'en-us'  │ 'Female' │        │ 'B'           │ 'C'          │
#│ af_river    │ 'River'    │ 'en-us'  │ 'Female' │        │ 'C'           │ 'D'          │
#│ af_sarah    │ 'Sarah'    │ 'en-us'  │ 'Female' │        │ 'B'           │ 'C+'         │
#│ af_sky      │ 'Sky'      │ 'en-us'  │ 'Female' │        │ 'B'           │ 'C-'         │
#│ am_adam     │ 'Adam'     │ 'en-us'  │ 'Male'   │        │ 'D'           │ 'F+'         │
#│ am_echo     │ 'Echo'     │ 'en-us'  │ 'Male'   │        │ 'C'           │ 'D'          │
#│ am_eric     │ 'Eric'     │ 'en-us'  │ 'Male'   │        │ 'C'           │ 'D'          │
#│ am_fenrir   │ 'Fenrir'   │ 'en-us'  │ 'Male'   │        │ 'B'           │ 'C+'         │
#│ am_liam     │ 'Liam'     │ 'en-us'  │ 'Male'   │        │ 'C'           │ 'D'          │
#│ am_michael  │ 'Michael'  │ 'en-us'  │ 'Male'   │        │ 'B'           │ 'C+'         │
#│ am_onyx     │ 'Onyx'     │ 'en-us'  │ 'Male'   │        │ 'C'           │ 'D'          │
#│ am_puck     │ 'Puck'     │ 'en-us'  │ 'Male'   │        │ 'B'           │ 'C+'         │
#│ am_santa    │ 'Santa'    │ 'en-us'  │ 'Male'   │        │ 'C'           │ 'D-'         │
#│ bf_emma     │ 'Emma'     │ 'en-gb'  │ 'Female' │ '🚺'   │ 'B'           │ 'B-'         │
#│ bf_isabella │ 'Isabella' │ 'en-gb'  │ 'Female' │        │ 'B'           │ 'C'          │
#│ bm_george   │ 'George'   │ 'en-gb'  │ 'Male'   │        │ 'B'           │ 'C'          │
#│ bm_lewis    │ 'Lewis'    │ 'en-gb'  │ 'Male'   │        │ 'C'           │ 'D+'         │
#│ bf_alice    │ 'Alice'    │ 'en-gb'  │ 'Female' │ '🚺'   │ 'C'           │ 'D'          │
#│ bf_lily     │ 'Lily'     │ 'en-gb'  │ 'Female' │ '🚺'   │ 'C'           │ 'D'          │
#│ bm_daniel   │ 'Daniel'   │ 'en-gb'  │ 'Male'   │ '🚹'   │ 'C'           │ 'D'          │
#│ bm_fable    │ 'Fable'    │ 'en-gb'  │ 'Male'   │ '🚹'   │ 'B'           │ 'C'          │
#└─────────────┴────────────┴──────────┴──────────┴────────┴───────────────┴──────────────┘

[tts]
voices = [
  "af_heart", "af_alloy", "af_aoede", "af_bella", "af_jessica",
  "af_kore", "af_nicole", "af_nova", "af_river", "af_sarah",
  "af_sky", "am_adam", "am_echo", "am_eric", "am_fenrir",
  "am_liam", "am_michael", "am_onyx", "am_puck", "am_santa",
  "bf_emma", "bf_isabella", "bm_george", "bm_lewis", "bf_alice",
  "bf_lily", "bm_daniel", "bm_fable"
]
prefix = "voice"